### PR TITLE
Fix the rule that checks tickets per person

### LINKED ISSUE #891: Box Office Hold - The max per order on this hold is 4. I allocated one, then went back to allocate 2 more and got the error message that it exceeded the limit.
[https://www.bugherd.com/projects/154576/tasks/14](https://www.bugherd.com/projects/154576/tasks/14)

### PR DESCRIPTION
**Pull request by mikethetike**
### Closes Issues:
Closes #891 

### Migrations
 * No Migrations

### Environment Variables
 * No change

### CODE REVIEW

File: db/src/queries/quantity_of_tickets_per_user_per_event.sql [hunk 1]
```diff
@@ -1,18 +1,15 @@
...
+       CAST(COUNT(ticket_instances.id) AS INTEGER) AS total_quantity
+FROM orders
+         INNER JOIN
+     order_items ON (order_items.order_id = orders.id)
+         INNER JOIN
+     ticket_instances ON (ticket_instances.order_item_id = order_items.id)
+WHERE ((orders.user_id = $1 AND orders.on_behalf_of_user_id IS NULL) OR orders.on_behalf_of_user_id = $1)
+  AND order_items.event_id = $2
+  AND order_items.ticket_type_id IS NOT NULL
+  AND (ticket_instances.status = 'Purchased' OR
```
Comment (Timo614) [inline db/src/queries/quantity_of_tickets_per_user_per_event.sql]: Should this also check for the `Redeemed` tickets?
